#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  vars_files:
    - secret.yml

  tasks:
    - name: install nginx
      apt: name=nginx state=present
    - name: install python3 and virtualenv
      apt: name={{item}} state=present
      with_items:
        - python3.8
        - python3-virtualenv
    - name: install postgres
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-contrib
    - name: "Install Python packages"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary 
    - name: start postgresql
      service: 
          name: postgresql
          state: started
          enabled: yes
    - name: create postgres db
      postgresql_db:
        state: present
        name: "luma_{{luma_project}}"
      become: yes
      become_user: postgres
    - name: create postgres user
      postgresql_user:
        state: present
        name: "{{luma_project}}"
        password: "{{user_password}}"
      become: yes
      become_user: postgres
    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "luma_{{luma_project}}"
        roles: "{{luma_project}}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres
    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "/etc/postgresql/12/main/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{luma_project}}"
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres
    - name: "Allow peer connection for the db user"
      postgresql_pg_hba:
        dest: "/etc/postgresql/12/main/pg_hba.conf"
        contype: local
        databases: all
        method: trust
        users: "{{luma_project}}"
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres
    - name: clone project
      git:
        clone: yes
        repo: "{{luma_git}}"
        dest: "~/luma_{{luma_project}}"
    - name: create virtualenvs directory
      file:
        path: /envs
        state: directory
    - name: create virtualenv for project
      command:
        creates: "/envs/{{luma_project}}"
        cmd: "virtualenv /envs/{{luma_project}}"
    - name: install dependencies for luma
      pip:
        requirements: "~/luma_{{luma_project}}/requirements.txt"
        virtualenv: "/envs/{{luma_project}}"
        virtualenv_python: python3
    - name: change permissions for media and public
      file:
        path: "~/luma_{{luma_project}}"
        owner: "root"
        group: "www-data"
        mode: 644
        recurse: yes
    - name: update allowed_hosts in settings.py
      replace:
        path: "~/luma_{{luma_project}}/luma/settings.py"
        regexp: 'ALLOWED_HOSTS = \[.*\]'
        replace: "ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '{{root_host}}']"
    - name: update database name in settings.py
      replace:
        path: "~/luma_{{luma_project}}/luma/settings.py"
        regexp: "'NAME': '.*'"
        replace: "'NAME': 'luma_{{luma_project}}'"
    - name: update database password in settings.py
      replace:
        path: "~/luma_{{luma_project}}/luma/settings.py"
        regexp: "'USER': '.*'"
        replace: "'USER': '{{luma_project}}'"
    - name: update database password in settings.py
      replace:
        path: "~/luma_{{luma_project}}/luma/settings.py"
        regexp: "'PASSWORD': '.*'"
        replace: "'PASSWORD': '{{user_password}}'"
    - name: run makemigrations
      command:
        chdir: "~/luma_{{luma_project}}"
        cmd: "/envs/{{luma_project}}/bin/python3 manage.py makemigrations"
    - name: run migrate
      command:
        chdir: "~/luma_{{luma_project}}"
        cmd: "/envs/{{luma_project}}/bin/python3 manage.py migrate"
    - name: create luma project socket file
      template:
        src: templates/luma.socket.j2
        dest: /etc/systemd/system/luma_{{luma_project}}.socket
    - name: create luma project service file
      template:
        src: templates/luma.service.j2
        dest: /etc/systemd/system/luma_{{luma_project}}.service
    - name: enable and start luma socket
      service:
        name: luma_{{luma_project}}.socket
        state: started
        enabled: yes
        daemon_reload: yes
    - name: enable and start luma service
      service:
        name: luma_{{luma_project}}.service
        state: started
        enabled: yes
        daemon_reload: yes
    - name: create nginx config
      template:
        src: templates/luma.website.j2
        dest: /etc/nginx/sites-available/{{root_host}}.conf
    - name: enable webapp with nginx
      file:
        src: /etc/nginx/sites-available/{{root_host}}.conf
        dest: /etc/nginx/sites-enabled/{{root_host}}.conf
        state: link
    - name: install snap
      apt:
        name: snapd
        state: present
    - name: install cerbot
      community.general.snap:
        name: certbot
        classic: yes
        state: present
    - name: start nginx
      service:
          name: nginx
          state: restarted
          enabled: yes
    


  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted