#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  vars_files:
    - secret.yml

  tasks:
    - name: install nginx
      apt: name=nginx state=present
    - name: install postgres
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-contrib
    - name: "Install Python packages"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql
    - name: install python3 and virtualenv
      apt: name={{item}} state=present
      with_items:
        - python3
        - python3-virtualenv
    - name: start postgresql
      service:
          name: postgresql
          state: started
    - name: create postgres db
      postgresql_db:
        state: present
        name: "luma_{{luma_project}}"
      become: yes
      become_user: postgres
    - name: create postgres user
      postgresql_user:
        state: present
        name: "{{luma_project}}"
        password: "{{user_password}}"
      become: yes
      become_user: postgres
    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "luma_{{luma_project}}"
        roles: "{{luma_project}}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres
    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{luma_project}}"
        create: true
      become: yes
      become_user: postgres
      notify: restart postgres
    - name: start nginx
      service:
          name: nginx
          state: started


  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted